[package]
name = "diskspace_free"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.5"
ratatui = { version = "0.26.1", features = ["all-widgets"] }
crossterm = "0.27.0"
tokio = { version = "1.36.0", features = ["full"] }
is-admin = "0.1.1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
